spring.application.name=transaction-service
server.port=8089
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#  database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/bank_transaction_db
spring.datasource.username=root
spring.datasource.password=Sujit@6299

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT config - must match authentication-authorization-service
jwt.secret=scuihuw4u8u89243ufwcuh2ufhcjij09298r4hicwnih9i29kioviuhiuj3jionvjn

eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

#eureka
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1